---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-hub-via-jenkins
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: docker-hub-via-jenkins
    spec:
      containers:
      - name: docker-hub-via-jenkins
        image: superleague16789/sl-kub-pankaj1:latest
        ports:
        - containerPort: 8080
...

---
apiVersion: v1
kind: Service
metadata:
  name: docker-hub-via-jenkins-svc
spec:
  type: Loadbalencer
  selector:
    app: docker-hub-via-jenkins-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9339
...
